name: Holiday Extras Tech
description: Holiday Extras Tech Team Blog
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
url: http://tech.holidayextras.co.uk
baseurl:
paginate: 10
exclude: ["node_modules","package.json","README.md", "Gemfile"]
collections:
  jobs:
    output: true
    permalink: /careers/:path/
defaults:
  - scope:
      path: ""
      collections: jobs
    values:
      layout: page
gems:
  - jekyll-redirect-from
  - jekyll-paginate
prose:
  rooturl: ''
  siteurl: 'http://tech.holidayextras.co.uk'
  ignore:
    - _data
    - _includes
    - /_layouts
    - /_includes
    - /_site
    - assets
    - css
    - js
    - less
    - .gitignore
    - _config.yml
    - _config_dev.yml
    - browserconfig.xml
    - CNAME
    - favicon.ico
    - feed.xml
    - Gemfile
    - Gemfile.lock
    - holidayextras.sublime-project
    - index.html
    - package.json
  media: 'assets/img'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "comments"
        field:
          element: "hidden"
          value: "true"
      - name: "author"
        field:
          element: "text"
          type: "text"
          label: "Your full name"
      - name: "categories"
        field:
          element: "text"
          type: "text"
          placeholder: "NodeJS"
          label: "Categories"
      - name: "tags"
        field:
          element: "text"
          type: "text"
          label: "Searchable tags"
